// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_GhostScreen();
Q_GHS_KEEP_REFERENCE(qml_register_types_GhostScreen)

class GhostScreenPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    GhostScreenPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_GhostScreen;
        Q_UNUSED(registration)
    }
};



#include "GhostScreenplugin_GhostScreenPlugin.moc"
